### ISSUE TITLE
QC cut implementation

### ISSUE THREAD

**Issue by hervasa2** [legend-exp/LegendDSP.jl#20]
Pile-up rejection (https://github.com/legend-exp/LegendDSP.jl/blob/c322eb0d68c90d99c63f5868c7bf18f5a0f280d6/src/dsp_icpc.jl#L195C5-L204C54) currently uses an intersect with the settings, `flt_intersec_inTrace = Intersect(mintot = 100u"ns")`, of the current waveform (`wvfs_sgflt_deriv`). Given `mintot = 100u"ns"`  this will also tag multi-site events as pile-up. To remedy this I suggest setting `mintot` to at least the maximum rise time of the detector and at most the maximum drift time of the detector. Alternatively the the waveform could be filtered with a trapezoidal filter with flat time set to around the same value. 

Question, should I add data cleaning routines at this level?

**Comment by theHenks** [comment]
The `flt_intersec_inTrace` is just an estimator for later processing to generate a pileup rejection cut. What is used in the higher tiers later is the following:
```    
inTrace_qc = .!(data.inTrace_intersect .> data.t0 .+ 2 .* data.drift_time .&& data.inTrace_n .> 1)
```
This is currently here: https://github.com/legend-exp/LegendSpecFits.jl/blob/dev/src/qc.jl 
This is my current "something take works" thing for QC cuts in `cal`. For `phy` there we need something else. In general, I suggest the following approach:
- Extend the `dsp_icpc` script with the raw DSP parameter you think we need for QC tags. I will move more stuff towards single subroutines, so maybe just a function somewhere which calculates the stuff (s. `dsp_routines.jl`) which can then be included in the `dsp_icpc` function. Also if you need metadata input, this can be provided via the `DSPConfig`. 
- Then calculate parameters based on that in the parameter extraction step (e.g. the baseline mean distribution sigma etc.) via functionality from the `LegendSpecFits.jl` package. There should be everything already ready to go to do all kind of fits to distributions, only thing missing is the actual routines. 
- Finally, set up a QC tags in a metadata format with Olis "create PropertyFunctions from json files" thing in `LegendDataManagement.jl`. It can basically parse expressions and apply them to Tables (e.g. DSP output table) so that we have a metadata way of defining and applying QC cuts. (https://github.com/legend-exp/LegendDataManagement.jl/blob/main/src/ljl_expressions.jl)
- Put all of this into the dataflow (I can help there), and then create hit files.

What do you think?

**Comment by hervasa2** [comment]
Sorry I was looking at the `main` branch of `LegendSpecFits.jl` and not `dev` so I had not seen the pileup code. Very nice, I really like the approach! However I think we should use the same pileup tag (and all qc in general) for `phys` and `cal`. 

Thank you for the list of recommended steps, I will start to work on this. I like the architecture :)

**Comment by theHenks** [comment]
I am not sure about that yet. Pygama also has different sets there, and uses more strict cuts for the cal parameter extraction. But we can think about it. So far, these QC cuts defined in the SpecFits package are exclusively for calibration data. 
So we can see. I just would like to move that stuff into a certain functionality where you can easily define cuts based on some metadata input with `.json` files.

**Comment by hervasa2** [comment]
But then how do we get cut efficiencies in `phys`? I see the motivation to use different cut values for `cal` and `phys`, but I think its the wrong approach. We should use calibrations to validate the qc cuts. After a cut is defined in `cal` we test it in `phys` then if the sacrifice is to high we go back to `cal` and rethink.

**Comment by theHenks** [comment]
I think we can close this here for now, since the stuff is included now.
